version: '3.5'
services:
  backend:
    image: backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  frontend:
    image: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
      # - "27018:27017" changed port
    volumes:
      - /home/mayank1609/GameShopDevOps/data/db:/data/db:rw
      # - /home/gandalf/GameShopDevOps/data/db:/data/db:rw