version: '3.5'
services:
  frontend:
    image: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    # volumes:
    #   - /mnt/d/code/sem7/spe/GameShopDevOps/data/db:/data/db:rw